CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"userId" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp,
	"refreshTokenExpiresAt" timestamp,
	"scope" text,
	"password" text,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "request" (
	"id" text PRIMARY KEY NOT NULL,
	"make" text NOT NULL,
	"vehicle_model" text NOT NULL,
	"condition" text DEFAULT 'New' NOT NULL,
	"yearFrom" integer,
	"yearTo" integer,
	"mileage" text,
	"specs" text,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"countryCode" text NOT NULL,
	"phone" text NOT NULL,
	"countryOfImport" text NOT NULL,
	"importTimeline" text,
	"dossierIds" text[] DEFAULT '{}' NOT NULL,
	"contactMethods" text[] DEFAULT '{}' NOT NULL,
	"contactDays" text[] DEFAULT '{}' NOT NULL,
	"contactTimeWindow" text,
	"contactTimezone" text,
	"contactTimezoneLabel" text,
	"preferredContactAt" timestamp,
	"isDraft" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'New' NOT NULL,
	"leadStatus" text DEFAULT 'Action required' NOT NULL,
	"statusUpdatedAt" timestamp,
	"options" text,
	"agreedPrice" double precision,
	"statusHistory" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"paymentType" text,
	"totalAmount" double precision,
	"advancePaymentAmount" double precision,
	"balancePaymentAmount" double precision,
	"balancePaymentStage" text,
	"depositAmount" double precision,
	"transactionId" text,
	"invoiceNumber" text,
	"inspectionNotes" text,
	"trackingNumber" text,
	"vesselName" text,
	"eta" timestamp,
	"portName" text,
	"containerNumber" text,
	"portOfArrival" text,
	"customsNotes" text,
	"adminNotes" text,
	"source" text,
	"followUpAt" timestamp,
	"followUpSetAt" timestamp,
	"gclid" text,
	"fbclid" text,
	"fbc" text,
	"fbp" text,
	"assignedToId" text,
	"assignedToName" text,
	"assignmentMethod" text DEFAULT 'round-robin' NOT NULL,
	"documents" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "salesprofile" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"slug" text NOT NULL,
	"isPublished" boolean DEFAULT false NOT NULL,
	"displayName" text NOT NULL,
	"headline" text NOT NULL,
	"tagline" text NOT NULL,
	"bio" text NOT NULL,
	"photoUrl" text NOT NULL,
	"coverImageUrl" text NOT NULL,
	"yearsExperience" integer DEFAULT 0 NOT NULL,
	"languages" text[] DEFAULT '{}' NOT NULL,
	"expertise" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sourcingCountries" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"trackRecord" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"testimonials" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"featuredDossierIds" text[] DEFAULT '{}' NOT NULL,
	"whatsappNumber" text NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "salesprofile_userId_unique" UNIQUE("userId"),
	CONSTRAINT "salesprofile_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"token" text NOT NULL,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"userId" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "socialpost" (
	"id" text PRIMARY KEY NOT NULL,
	"url" text NOT NULL,
	"shortcode" text NOT NULL,
	"page" text NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sourcinganalysis" (
	"id" text PRIMARY KEY NOT NULL,
	"make" text NOT NULL,
	"vehicleModel" text NOT NULL,
	"edition" text,
	"year" integer,
	"mileage" integer,
	"landedCostGbp" double precision NOT NULL,
	"currency" text DEFAULT 'JPY' NOT NULL,
	"dutyBasis" text,
	"vatBasis" text,
	"sources" text[] DEFAULT '{}' NOT NULL,
	"listingCount" integer DEFAULT 0 NOT NULL,
	"matchUsed" text,
	"widened" boolean DEFAULT false NOT NULL,
	"marketMin" double precision,
	"marketMedian" double precision,
	"marketMean" double precision,
	"marketMax" double precision,
	"recommendation" text NOT NULL,
	"headline" text,
	"reasoning" text,
	"confidence" text,
	"grossMargin" double precision,
	"marginPct" double precision,
	"createdById" text,
	"createdByName" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "specdossier" (
	"id" text PRIMARY KEY NOT NULL,
	"make" text NOT NULL,
	"model" text NOT NULL,
	"year" text DEFAULT '' NOT NULL,
	"trim" text DEFAULT '' NOT NULL,
	"condition" text DEFAULT 'New' NOT NULL,
	"mileage" text DEFAULT '' NOT NULL,
	"countryOfOrigin" text DEFAULT 'Japan' NOT NULL,
	"engineConfig" text DEFAULT '' NOT NULL,
	"displacement" text DEFAULT '' NOT NULL,
	"maxPower" text DEFAULT '' NOT NULL,
	"maxTorque" text DEFAULT '' NOT NULL,
	"transmission" text DEFAULT '' NOT NULL,
	"fuelSystem" text DEFAULT 'Petrol' NOT NULL,
	"steering" text DEFAULT 'RHD' NOT NULL,
	"emissions" text DEFAULT '' NOT NULL,
	"pricing" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"upholstery" text DEFAULT '' NOT NULL,
	"infotainment" text DEFAULT '' NOT NULL,
	"features" text[] DEFAULT '{}' NOT NULL,
	"searchTags" text[] DEFAULT '{}' NOT NULL,
	"heroImageUrl" text DEFAULT '' NOT NULL,
	"images" text[] DEFAULT '{}' NOT NULL,
	"customData" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"valuePoints" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"slug" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'Draft' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"emailVerified" boolean NOT NULL,
	"image" text,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"role" text DEFAULT 'user' NOT NULL,
	"isBanned" boolean DEFAULT false NOT NULL,
	"badges" text[] DEFAULT '{}' NOT NULL,
	"whatsappNumber" text DEFAULT '',
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"createdAt" timestamp,
	"updatedAt" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "request" ADD CONSTRAINT "request_assignedToId_user_id_fk" FOREIGN KEY ("assignedToId") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "salesprofile" ADD CONSTRAINT "salesprofile_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "page_order_idx" ON "socialpost" USING btree ("page","order");