"use client";

import { useEffect, useRef } from "react";
import {
  GLOBE_PLACES,
  GLOBE_PLACES_BY_ID,
  GLOBE_ROUTES,
  type GlobePlace,
  type GlobeRoute,
} from "@/config/globe";
import {
  angleBetween,
  arcPoint,
  fibonacciSphere,
  isLand,
  type LandMask,
  latLngToVec3,
  liftFactor,
  project,
  rotateX,
  rotateY,
  type Vec3,
} from "@/lib/globe/geo";

/**
 * Canvas-2D dot globe: a rotating sphere of land dots with shipments animating
 * along great-circle arcs between the countries in src/config/globe.ts.
 *
 * ## Why canvas and not Three.js
 *
 * Stripe's globe is WebGL because it draws ~20,000 dots with per-country shader
 * animation. At the ~3,500 dots this needs, canvas holds 60fps comfortably and
 * costs no bundle — Three.js would be ~150KB gzipped for one marketing visual on
 * a site that already ships framer-motion.
 *
 * ## How the land is drawn
 *
 * Same trick as Stripe's: points are distributed over the sphere with a
 * Fibonacci spiral (see geo.ts for why not a lat/lng grid), then each one is
 * tested against an equirectangular PNG of the world via getImageData. Dots that
 * land in the ocean are discarded at setup, so the animation loop only ever
 * walks real geography.
 *
 * The mask is generated by scripts/generate-land-mask.mjs and cached at module
 * scope, so several globes on one page decode it once.
 *
 * ## Adding countries
 *
 * Don't edit this file — add to GLOBE_PLACES / GLOBE_ROUTES in
 * src/config/globe.ts. Everything here is driven from that registry.
 */

export type GlobePalette = {
  /** Land dots, near side. */
  dot: string;
  /** The sphere itself, behind the dots. */
  ocean: string;
  /** Thin ring around the limb. */
  limb: string;
  /** Marker fills by role. */
  source: string;
  hub: string;
  destination: string;
  /** Arc colours, cycled per route. */
  arcs: string[];
};

/** Matches .pa-headline-gradient / .pa-mesh in globals.css. */
export const GLOBE_PALETTE_LIGHT: GlobePalette = {
  dot: "24, 24, 27",
  ocean: "rgba(244, 244, 245, 0.55)",
  limb: "rgba(161, 161, 170, 0.35)",
  source: "#0ea5e9",
  hub: "#8b5cf6",
  destination: "#ec4899",
  arcs: ["#0ea5e9", "#8b5cf6", "#ec4899", "#2dd4bf"],
};

export const GLOBE_PALETTE_DARK: GlobePalette = {
  dot: "228, 228, 231",
  ocean: "rgba(24, 24, 27, 0.65)",
  limb: "rgba(113, 113, 122, 0.45)",
  source: "#38bdf8",
  hub: "#a78bfa",
  destination: "#f472b6",
  arcs: ["#38bdf8", "#a78bfa", "#f472b6", "#5eead4"],
};

const MASK_SRC = "/globe/land-mask.png";

let maskPromise: Promise<LandMask> | null = null;

/** Decodes the land mask once per page, however many globes ask for it. */
function loadLandMask(): Promise<LandMask> {
  if (maskPromise) return maskPromise;
  maskPromise = new Promise((resolve, reject) => {
    const image = new Image();
    image.decoding = "async";
    image.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = image.naturalWidth;
      canvas.height = image.naturalHeight;
      const ctx = canvas.getContext("2d", { willReadFrequently: true });
      if (!ctx) {
        reject(new Error("2d context unavailable for land mask"));
        return;
      }
      ctx.drawImage(image, 0, 0);
      const { data, width, height } = ctx.getImageData(
        0,
        0,
        canvas.width,
        canvas.height,
      );
      resolve({ data, width, height });
    };
    image.onerror = () => reject(new Error(`Failed to load ${MASK_SRC}`));
    image.src = MASK_SRC;
  });
  return maskPromise;
}

type Props = {
  places?: GlobePlace[];
  routes?: GlobeRoute[];
  /**
   * Candidate points spread over the whole sphere. Roughly 29% survive the land
   * test, so 16,000 gives ~4,600 drawn dots. Raise for a denser surface at a
   * linear cost per frame.
   */
  dotCount?: number;
  /** Axial lean in radians. */
  tilt?: number;
  /** Radians per second. */
  speed?: number;
  /** Drag to spin. */
  interactive?: boolean;
  palette?: GlobePalette;
  className?: string;
};

export default function DotGlobe({
  places = GLOBE_PLACES,
  routes = GLOBE_ROUTES,
  dotCount = 16000,
  tilt = 0.32,
  speed = 0.055,
  interactive = true,
  palette = GLOBE_PALETTE_LIGHT,
  className = "",
}: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const wrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    const wrap = wrapRef.current;
    if (!canvas || !wrap) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const reduceMotion = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;

    let cancelled = false;
    let frame = 0;
    let width = 0;
    let height = 0;

    // Rotation state. `spin` is the live angle; `velocity` carries drag inertia
    // and decays back to the idle speed when the pointer is released.
    let spin = -1.2;
    let velocity = 0;
    let dragging = false;
    let lastPointerX = 0;
    let onScreen = true;

    // Flat typed arrays rather than objects: the loop rotates every dot each
    // frame, and allocating ~3,500 objects 60 times a second is the difference
    // between a smooth globe and a GC sawtooth.
    let dotX = new Float32Array(0);
    let dotY = new Float32Array(0);
    let dotZ = new Float32Array(0);

    const markers = places.map((place) => ({
      place,
      vec: latLngToVec3(place),
      colour:
        place.role === "source"
          ? palette.source
          : place.role === "hub"
            ? palette.hub
            : palette.destination,
    }));

    // Routes are pre-resolved to vectors, and each gets a phase offset so the
    // shipments don't all depart on the same beat. Longer legs take longer,
    // which is both truer and easier to read than a uniform speed.
    const lanes = routes
      .map((route, index) => {
        const from = GLOBE_PLACES_BY_ID.get(route.from);
        const to = GLOBE_PLACES_BY_ID.get(route.to);
        if (!from || !to) return null;
        const a = latLngToVec3(from);
        const b = latLngToVec3(to);
        return {
          a,
          b,
          duration: 2.6 + angleBetween(a, b) * 1.9,
          phase: (index * 0.618) % 1,
          colour: palette.arcs[index % palette.arcs.length],
        };
      })
      .filter((lane): lane is NonNullable<typeof lane> => lane !== null);

    // These are arrow consts, not `function` declarations, so TypeScript keeps
    // the non-null narrowing of `canvas` / `ctx` / `wrap` from the guards above.
    // A hoisted declaration could in principle be called before those guards ran,
    // so narrowing is discarded inside one.
    const resize = () => {
      const rect = wrap.getBoundingClientRect();
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      width = rect.width;
      height = rect.height;
      canvas.width = Math.round(width * dpr);
      canvas.height = Math.round(height * dpr);
      canvas.style.width = `${width}px`;
      canvas.style.height = `${height}px`;
      // Draw in CSS pixels; the transform handles the device ratio.
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };

    /**
     * Fades surface geometry across the limb instead of clipping it hard. Safe
     * to let this run slightly negative: a marker sits at radius 1, so it can
     * never project outside the disc however far round it goes.
     */
    const depthAlpha = (z: number) => {
      return Math.max(0, Math.min(1, (z + 0.12) / 0.32));
    };

    /**
     * The same, for lifted geometry. Arcs are drawn at up to 1.2x the radius, so
     * a point whose ground track has merely reached the limb already projects
     * well outside the globe — this reaches zero at z = 0 so an arc is gone by
     * the time it could escape the disc.
     */
    const arcAlpha = (z: number) => {
      return Math.max(0, Math.min(1, z / 0.18));
    };

    const draw = (elapsed: number) => {
      const radius = Math.min(width, height) * 0.42;
      const cx = width / 2;
      const cy = height / 2;
      ctx.clearRect(0, 0, width, height);

      // Ocean sphere.
      const sphere = ctx.createRadialGradient(
        cx - radius * 0.35,
        cy - radius * 0.4,
        radius * 0.1,
        cx,
        cy,
        radius,
      );
      sphere.addColorStop(0, palette.ocean);
      sphere.addColorStop(1, "rgba(0,0,0,0)");
      ctx.fillStyle = sphere;
      ctx.beginPath();
      ctx.arc(cx, cy, radius, 0, Math.PI * 2);
      ctx.fill();

      ctx.strokeStyle = palette.limb;
      ctx.lineWidth = 1;
      ctx.stroke();

      // Land dots.
      const cos = Math.cos(spin);
      const sin = Math.sin(spin);
      const cosT = Math.cos(tilt);
      const sinT = Math.sin(tilt);
      const dotSize = Math.max(1, radius * 0.0075);

      for (let i = 0; i < dotX.length; i += 1) {
        const x0 = dotX[i];
        const y0 = dotY[i];
        const z0 = dotZ[i];
        // rotateY then rotateX, inlined.
        const rx = x0 * cos + z0 * sin;
        const rz = z0 * cos - x0 * sin;
        const ry = y0 * cosT - rz * sinT;
        const rz2 = y0 * sinT + rz * cosT;
        if (rz2 <= 0) continue;
        const alpha = 0.12 + rz2 * 0.5;
        ctx.fillStyle = `rgba(${palette.dot}, ${alpha.toFixed(3)})`;
        ctx.fillRect(
          cx + rx * radius - dotSize / 2,
          cy - ry * radius - dotSize / 2,
          dotSize,
          dotSize,
        );
      }

      const orient = (v: Vec3) => rotateX(rotateY(v, spin), tilt);

      // Arcs. Each lane draws only the live trail, not the whole path, so the
      // globe reads as traffic rather than as a wireframe.
      const SEGMENTS = 18;
      const TRAIL = 0.28;
      // How far above the surface an arc bows at its midpoint, as a fraction of
      // the radius. Much past 0.25 and long routes read as loops floating free of
      // the globe rather than as flight paths over it.
      const ARC_LIFT = 0.2;
      // An arc is culled by where its ground track is, not by where the raised
      // line is — see liftFactor. So each sample is taken on the surface (lift 0),
      // depth-tested there, and only then pushed outwards to draw.
      const sampleArc = (lane: (typeof lanes)[number], t: number) => {
        const ground = orient(arcPoint(lane.a, lane.b, t, 0));
        const fade = arcAlpha(ground.z);
        const k = liftFactor(t, ARC_LIFT);
        return {
          fade,
          point: project(
            { x: ground.x * k, y: ground.y * k, z: ground.z * k },
            radius,
            cx,
            cy,
          ),
        };
      };

      for (const lane of lanes) {
        const head = (((elapsed / lane.duration + lane.phase) % 1) + 1) % 1;
        ctx.lineCap = "round";
        for (let s = 0; s < SEGMENTS; s += 1) {
          const t0 = Math.max(0, head - TRAIL * (1 - s / SEGMENTS));
          const t1 = Math.min(1, head - TRAIL * (1 - (s + 1) / SEGMENTS));
          if (t1 <= 0) continue;
          const a0 = sampleArc(lane, t0);
          const a1 = sampleArc(lane, t1);
          const fade = Math.min(a0.fade, a1.fade);
          if (fade <= 0) continue;
          ctx.globalAlpha = fade * (s / SEGMENTS) ** 1.5;
          ctx.strokeStyle = lane.colour;
          ctx.lineWidth = 1.4;
          ctx.beginPath();
          ctx.moveTo(a0.point.x, a0.point.y);
          ctx.lineTo(a1.point.x, a1.point.y);
          ctx.stroke();
        }

        // The shipment itself.
        const tip = sampleArc(lane, head);
        if (tip.fade > 0) {
          ctx.globalAlpha = tip.fade;
          ctx.fillStyle = lane.colour;
          ctx.beginPath();
          ctx.arc(tip.point.x, tip.point.y, 2.1, 0, Math.PI * 2);
          ctx.fill();
        }
        ctx.globalAlpha = 1;
      }

      // Markers, with a slow pulse so the map feels live even when an arc is
      // between runs.
      for (const marker of markers) {
        const v = orient(marker.vec);
        const fade = depthAlpha(v.z);
        if (fade <= 0) continue;
        const p = project(v, radius, cx, cy);
        const pulse =
          0.5 +
          0.5 * Math.sin(elapsed * 1.8 + marker.vec.x * 4 + marker.vec.y * 3);

        ctx.globalAlpha = fade * (0.18 + pulse * 0.22);
        ctx.fillStyle = marker.colour;
        ctx.beginPath();
        ctx.arc(p.x, p.y, 3.2 + pulse * 3.4, 0, Math.PI * 2);
        ctx.fill();

        ctx.globalAlpha = fade;
        ctx.beginPath();
        ctx.arc(p.x, p.y, 2, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.globalAlpha = 1;
    };

    let previous = 0;
    const tick = (now: number): void => {
      if (cancelled) return;
      const dt = previous ? Math.min((now - previous) / 1000, 0.05) : 0;
      previous = now;

      if (dragging) {
        // Held: the pointer owns the angle.
      } else {
        velocity += (speed - velocity) * Math.min(1, dt * 2.5);
        spin += velocity * dt;
      }

      draw(now / 1000);
      frame = requestAnimationFrame(tick);
    };

    const onPointerDown = (event: PointerEvent) => {
      if (!interactive) return;
      dragging = true;
      lastPointerX = event.clientX;
      canvas.setPointerCapture(event.pointerId);
    };
    const onPointerMove = (event: PointerEvent) => {
      if (!dragging) return;
      const delta = event.clientX - lastPointerX;
      lastPointerX = event.clientX;
      spin += delta * 0.005;
      velocity = delta * 0.25;
    };
    const onPointerUp = (event: PointerEvent) => {
      if (!dragging) return;
      dragging = false;
      if (canvas.hasPointerCapture(event.pointerId)) {
        canvas.releasePointerCapture(event.pointerId);
      }
    };

    const resizeObserver = new ResizeObserver(() => {
      resize();
      if (reduceMotion || !onScreen) draw(0);
    });
    resizeObserver.observe(wrap);

    // Off-screen globes cost nothing. Stripe debounced on scroll for the same
    // reason; an observer is cheaper and more precise.
    const visibility = new IntersectionObserver(
      ([entry]) => {
        onScreen = entry.isIntersecting;
        if (reduceMotion) return;
        if (onScreen && !frame) {
          previous = 0;
          frame = requestAnimationFrame(tick);
        } else if (!onScreen && frame) {
          cancelAnimationFrame(frame);
          frame = 0;
        }
      },
      { rootMargin: "120px" },
    );
    visibility.observe(wrap);

    resize();

    loadLandMask()
      .then((mask) => {
        if (cancelled) return;
        const land = fibonacciSphere(dotCount).filter((point) =>
          isLand(mask, point),
        );
        dotX = new Float32Array(land.length);
        dotY = new Float32Array(land.length);
        dotZ = new Float32Array(land.length);
        land.forEach((point, i) => {
          const v = latLngToVec3(point);
          dotX[i] = v.x;
          dotY[i] = v.y;
          dotZ[i] = v.z;
        });

        if (reduceMotion) {
          // One composed frame, no loop.
          draw(0);
          return;
        }
        if (onScreen && !frame) frame = requestAnimationFrame(tick);
      })
      .catch(() => {
        // A missing mask shouldn't take the page with it — the ocean sphere and
        // the arcs still render, just without continents.
        if (!cancelled && !reduceMotion && onScreen && !frame) {
          frame = requestAnimationFrame(tick);
        }
      });

    if (interactive) {
      canvas.addEventListener("pointerdown", onPointerDown);
      canvas.addEventListener("pointermove", onPointerMove);
      canvas.addEventListener("pointerup", onPointerUp);
      canvas.addEventListener("pointercancel", onPointerUp);
    }

    return () => {
      cancelled = true;
      if (frame) cancelAnimationFrame(frame);
      resizeObserver.disconnect();
      visibility.disconnect();
      canvas.removeEventListener("pointerdown", onPointerDown);
      canvas.removeEventListener("pointermove", onPointerMove);
      canvas.removeEventListener("pointerup", onPointerUp);
      canvas.removeEventListener("pointercancel", onPointerUp);
    };
  }, [places, routes, dotCount, tilt, speed, interactive, palette]);

  const marketNames = places.map((place) => place.name).join(", ");

  return (
    <div
      ref={wrapRef}
      className={`relative aspect-square w-full ${className}`}
      role="img"
      aria-label={`Globe showing Providence Auto shipping routes to ${marketNames}`}
    >
      <canvas
        ref={canvasRef}
        className={interactive ? "cursor-grab active:cursor-grabbing" : ""}
      />
    </div>
  );
}
